# Generated by Django 2.1.7 on 2019-05-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='metric_id',
            new_name='metric',
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='contributors_id',
            new_name='contributors',
        ),
    ]
